<ul class="breadcrumb">
    <?php
    // iterator through the pages
    foreach ($this->pages as $key => $page) :

    // if this isn`t the last page, add a link and the separator
    if ($key < count($this->pages) - 1) :
    ?>
    <li>
        <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
        <!--<span class="divider">/</span>-->
     </li>
    <?php
    // otherwise, just output the name
    else :
    ?>
    <li class="active">
        <span><?php echo $page->getLabel(); ?></span>
    </li>
    <?php endif; ?>
    <?php endforeach; ?>
</ul>