<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?= $this->url($this->route); ?>?page=<?= $this->previous; ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?= $this->url($this->route); ?>?page=<?= $page; ?>">
                            <?= $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#">
                            <?= $page; ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?= $this->url($this->route); ?>?page=<?= $this->next; ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>
