<?php
     $title = "Edit Book";
     $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

    $form->setAttribute('action', $this->url(
        'book',
        array(
            'action'=> 'edit',
            'id' => $this->id
        )
    ));
    $form->prepare();

    echo $this->form()->openTag();
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('title'));
    echo $this->formRow($form->get('author'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();