<?php
  $title = "My Books";
  $this->headTitle($title);
?>

<h1>My Book List</h1>

<p>
    <a href="<?php echo $this->url('book', array('action' => 'add')); ?>">Add new book</a>
</p>

<table class="table">
    <tr>
        <td>Title</td>
        <td>Author</td>
        <td></td>
    </tr>
    <?php foreach($this->paginator as $book) : ?>
    <!-- loop on All Books Before Using Paginator Logic to Display Books -->
    <?php //foreach($books as $book) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($book->title) ?></td>
            <td><?php echo $this->escapeHtml($book->author) ?></td>
            <td>
                <a href="<?php echo $this->url('book',
                    array('action'=> 'edit', 'id' => $book->id)) ?>">Edit</a>
                <a href="<?php echo $this->url('book',
                    array('action'=> 'delete', 'id' => $book->id)) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
    // Call Pagination Control to create pagination layout
    // take parameters [ paginator object,
    //                   the scrolling style(three four scrolling style according to zend/paginator documentation),
    //                   partial layout for paginator,
    //                   the route which used into paginator links
    // ]
    echo $this->paginationControl(
        $this->paginator,
        'sliding',
        array('partial/paginator.phtml', 'book'),
        array(
            'route' => 'book'
        )
    );
?>